### ISSUE TITLE
Android3.0 Beta 4でFATAL ERROR in native method: processing of -javaagent failedエラー

### ISSUE THREAD

**Issue by imagepit** [SahaginOrg/sahagin-java#21]
Android3.0 Beta 4で`FATAL ERROR in native method: processing of -javaagent failed`エラーがでます。

## 環境

- MacOS 10.12.6
- Android Studio3.0 Beta4
![](https://www.evernote.com/l/AB3koH427dZKeYx6DJHBTkB3B8Z6PnsHO-YB/image.png)

## 事象

下記のGradleの設定で`./gradlew test`を実行すると、掲題のエラーが出ます。
Android2.3のときはエラーは出ませんでしたが、Android3.0 Beta4だとエラーがでます。

```
./gradlew test

> Task :app:compileDebugKotlin
Using kotlin incremental compilation

> Task :app:compileDebugUnitTestKotlin
Using kotlin incremental compilation

> Task :app:testDebugUnitTest
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/io/IOUtils
        at org.sahagin.share.CommonUtils.readManifestFromExternalJar(CommonUtils.java:171)
        at org.sahagin.runlib.srctreegen.SrcTreeGenerator.addToClassPathListFromJarManifest(SrcTreeGenerator.java:905)
        at org.sahagin.runlib.srctreegen.SrcTreeGenerator.addToClassPathList(SrcTreeGenerator.java:936)
        at org.sahagin.runlib.srctreegen.SrcTreeGenerator.generateWithRuntimeClassPath(SrcTreeGenerator.java:978)
        at org.sahagin.main.SahaginPreMain.generateAndDumpSrcTree(SahaginPreMain.java:107)
        at org.sahagin.main.SahaginPreMain.premain(SahaginPreMain.java:96)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.io.IOUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 12 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/io/IOUtils
        at org.sahagin.share.CommonUtils.readManifestFromExternalJar(CommonUtils.java:171)
        at org.sahagin.runlib.srctreegen.SrcTreeGenerator.addToClassPathListFromJarManifest(SrcTreeGenerator.java:905)
        at org.sahagin.runlib.srctreegen.SrcTreeGenerator.addToClassPathList(SrcTreeGenerator.java:936)
        at org.sahagin.runlib.srctreegen.SrcTreeGenerator.generateWithRuntimeClassPath(SrcTreeGenerator.java:978)
        at org.sahagin.main.SahaginPreMain.generateAndDumpSrcTree(SahaginPreMain.java:107)
        at org.sahagin.main.SahaginPreMain.premain(SahaginPreMain.java:96)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.io.IOUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 12 more
FATAL ERROR in native method: processing of -javaagent failed
Process 'Gradle Test Executor 4' finished with non-zero exit value 134
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 4' finished with non-zero exit value 134
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:380)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy103.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:213)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:325)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
<======-------> 51% EXECUTING [11m 14s]
> IDLE
```

## Gradle設定内容

Gradleの設定内容は下記のとおりです。

**build.gradle(Project)**

```
apply plugin: 'kotlin-android-extensions'
buildscript {
    ext.kotlin_version = '1.1.3-2'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**build.gradle(App)**

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "imagepit.com.kotlinsample"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    // Appium
    testImplementation 'org.seleniumhq.selenium:selenium-java:3.5.2'
    testImplementation 'io.appium:java-client:5.0.0'
    testImplementation 'org.ow2.asm:asm:5.2'
    testImplementation files('libs/sahagin-0.9.2.jar')
    testImplementation 'org.sahagin:sahagin:0.9.2'
}

tasks.withType(Test) {
    doFirst {
        jvmArgs '-javaagent:/Users/xxx/KotlinSample/app/libs/sahagin-0.9.2.jar'
    }
}
```

大変すばらしいプラグインも最新の環境でも使いたいので是非ご確認お願いいたします。

**Comment by NozomiIto** [comment]
Sorry but this issue page is only for English. I created the Japanese answer for this at https://github.com/SahaginOrg/japanese-forum/issues/5,  and please check this.

こちらのissueは英語のみサポートしております。日本語フォーラムの  https://github.com/SahaginOrg/japanese-forum/issues/5 にて回答を投稿しましたので、そちらをご確認・ご返信いただければ幸いです。
